dart-lang/co19

LibTest/io/Directory/stat_A01_t01.dart, LibTest/io/Directory/stat_A01_t02.dart, LibTest/io/File/stat_A01_t01.dart, LibTest/io/File/stat_A01_t02.dart, LibTest/io/FileStat/stat_A01_t01.dart, LibTest/io/FileStat/stat_A01_t02.dart, LibTest/io/Link/stat_A01_t01.dart, LibTest/io/Link/stat_A01_t02.dart
Fixes https://github.com/dart-lang/co19/issues/165
=> Wait with deleting file/directory until the test finished, only call asyncEnd() as the very last step

LibTest/io/HttpClientResponse/redirect_A01_t01.dart, LibTest/io/HttpClientResponse/redirect_A02_t01.dart, LibTest/io/HttpClientResponse/redirect_A03_t01.dart, LibTest/io/HttpClientResponse/redirect_A04_t01.dart, LibTest/io/HttpClientResponse/redirect_A05_t01.dart, LibTest/io/HttpClientResponse/redirect_A05_t02.dart, LibTest/io/HttpClientResponse/redirect_A05_t03.dart, LibTest/io/HttpClientResponse/redirects_A02_t01.dart, LibTest/io/HttpClientResponse/redirects_A02_t02.dart, LibTest/io/HttpClientResponse/redirects_A02_t04.dart, LibTest/io/HttpClientResponse/redirects_A02_t05.dart, LibTest/io/HttpClientResponse/redirects_A02_t06.dart
dart-lang/sdk#36900
https://github.com/dart-lang/co19/issues/383
=> More fixes to cast response to Stream<List<int>>

LibTest/io/InternetAddress/lookup_A01_t01.dart, LibTest/io/InternetAddress/lookup_A02_t01.dart, LibTest/io/InternetAddress/lookup_A02_t02.dart, LibTest/io/InternetAddress/lookup_A03_t01.dart, LibTest/io/InternetAddress/lookup_A03_t02.dart, LibTest/io/InternetAddress/lookup_A03_t03.dart, LibTest/io/InternetAddress/lookup_A03_t04.dart, LibTest/io/InternetAddress/lookup_A04_t01.dart, LibTest/io/NetworkInterface/list_A01_t01.dart, LibTest/io/NetworkInterface/list_A01_t02.dart, LibTest/io/NetworkInterface/list_A01_t03.dart, LibTest/io/NetworkInterface/list_A02_t01.dart, LibTest/io/NetworkInterface/list_A02_t02.dart, LibTest/io/NetworkInterface/list_A02_t03.dart
=> Replace InternetAddressType.ANY with InternetAddressType.any

LanguageFeatures/Enhanced-Enum/semantics_A09_t02.dart, LanguageFeatures/Enhanced-Enum/semantics_A09_t03.dart
This PR removes some of the extra expected CFE errors that are no longer reported by the CFE. The removal of the errors brings the behavior of the CFE in agreement to that of the Analyzer.
=> Remove extra expected CFE errors that are no longer reported

LanguageFeatures/Enhanced-Enum/grammar_A01_t02.dart, LanguageFeatures/Enhanced-Enum/grammar_A05_t01.dart, LanguageFeatures/Enhanced-Enum/semantics_A06_t07.dart, LanguageFeatures/Enhanced-Enum/semantics_A09_t04.dart, LanguageFeatures/Enhanced-Enum/semantics_A09_t06.dart, LanguageFeatures/Enhanced-Enum/semantics_A11_t01.dart
This PR adjusts the tests to account for reasonable discrepancies in error locations between the CFE and the Analyzer.
Part of https://github.com/dart-lang/co19/issues/1333.
=> Adjust locations of errors reported by CFE in Enhanced Enums tests

LanguageFeatures/Enhanced-Enum/implementing_enum_A03_t04.dart, LanguageFeatures/Enhanced-Enum/semantics_A11_t01.dart
This PR updates the expectations of the errors in some of the Enhanced Enums tests to match those emitted by the CFE after some recent updates in it.
=> Update expected errors after recent CFE udpates in Enhanced Enums

LibTest/io/HttpClient/findProxy_A01_t01.dart, LibTest/io/HttpClient/findProxy_A01_t02.dart, LibTest/io/HttpClient/findProxy_A02_t01.dart, LibTest/io/HttpClient/findProxy_A02_t02.dart
This is a co19_2 version of https://github.com/dart-lang/co19/pull/1383
=> #1129. In case of DIRECT connection don't expect any proxy routine called

LibTest/ffi/Size/Size_A01_t01.dart, LibTest/ffi/UintPtr/UintPtr_A01_t01.dart, LibTest/ffi/UintPtr/UintPtr_A01_t02.dart, LibTest/ffi/UnsignedChar/UnsignedChar_A01_t01.dart, LibTest/ffi/UnsignedInt/UnsignedInt_A01_t01.dart, LibTest/ffi/UnsignedLong/UnsignedLong_A01_t01.dart
Fixes https://github.com/dart-lang/sdk/issues/49648
=> #1388. FFI tests fixed for 32-bit systems

Language/Classes/definition_t14.dart
=> #1394. Add missing compile-error

LanguageFeatures/Records/type_inference_A01_t01.dart, LanguageFeatures/Records/type_inference_A02_t01.dart, LanguageFeatures/Records/type_promotion_A01_t01.dart, LanguageFeatures/Records/type_promotion_A01_t02.dart, LanguageFeatures/Records/type_promotion_A01_t03.dart, LanguageFeatures/Records/type_promotion_A02_t01.dart
I believe that this set of tests covers promotion and inference for records. If I missed anything and we need more tests, please, let me know
=> #1399. [Records] Type inference and promotion tests added

LibTest/io/RawDatagramSocket/bind_A02_t02.dart, LibTest/io/RawDatagramSocket/bind_A02_t04.dart, LibTest/io/RawDatagramSocket/bind_A02_t05.dart, LibTest/io/RawDatagramSocket/bind_A02_t06.dart, LibTest/io/RawDatagramSocket/bind_A02_t08.dart, LibTest/io/RawDatagramSocket/writeEventsEnable_A01_t01.dart, LibTest/io/RawDatagramSocket/writeEventsEnable_A01_t02.dart
Add changes made during the review from `co19_2` to `co19`
=> #195. Description some of RawDatagramSocket tests improved

LanguageFeatures/Records/interaction_with_legacy_A01_t01.dart, LanguageFeatures/Records/interaction_with_legacy_A02_t01.dart, LanguageFeatures/Records/interaction_with_legacy_A03_t01.dart, LanguageFeatures/Records/interaction_with_legacy_A04_t01.dart, LanguageFeatures/Records/interaction_with_legacy_A04_t02.dart, LanguageFeatures/Records/interaction_with_legacy_A04_t03.dart, LanguageFeatures/Records/interaction_with_legacy_A04_t04.dart
=> #1516. [Records] Experimental flags added to legacy libraries

Language/Mixins/Mixin_Application/syntax_t01.dart, Language/Mixins/Mixin_Application/syntax_t02.dart, Language/Mixins/Mixin_Application/syntax_t03.dart, Language/Mixins/Mixin_Application/syntax_t04.dart, Language/Mixins/Mixin_Application/syntax_t05.dart, Language/Mixins/Mixin_Application/syntax_t06.dart, Language/Mixins/Mixin_Application/syntax_t07.dart, Language/Mixins/Mixin_Application/syntax_t08.dart, Language/Mixins/Mixin_Application/syntax_t09.dart, Language/Mixins/Mixin_Application/syntax_t10.dart, Language/Mixins/Mixin_Application/syntax_t26.dart
There in an unrecognized character, I think it should be removed.
With IntelliJ, it is shown as
=> Remove unrecognized character.

LanguageFeatures/Patterns/map_A01_t01.dart, LanguageFeatures/Patterns/map_A01_t02.dart, LanguageFeatures/Patterns/map_A01_t03.dart, LanguageFeatures/Patterns/map_A01_t04.dart, LanguageFeatures/Patterns/map_A02_t01.dart, LanguageFeatures/Patterns/map_A02_t02.dart, LanguageFeatures/Patterns/map_A03_t01.dart, LanguageFeatures/Patterns/map_A04_t01.dart, LanguageFeatures/Patterns/map_A04_t02.dart, LanguageFeatures/Patterns/map_A05_t01.dart, LanguageFeatures/Patterns/map_A06_t01.dart, LanguageFeatures/Patterns/map_A07_t01.dart, LanguageFeatures/Patterns/map_A08_t01.dart
`LanguageFeatures/Patterns/map_A05_t01.dart` added, `map_A06*` and higher just renamed
=> #1401. [Patterns] Map patterns tests updated. Check primitive == for keys

Language/Expressions/Constants/static_constant_t06.dart, Language/Expressions/Constants/static_constant_t07.dart
When we are expecting compile-time error we shouldn't expect anything elese
=> #1575. Remove unused code

Language/Statements/Continue/label_t07.dart
This is the pre-nnbd for #1685
=> Update co19_2 test for `CONTINUE_LABEL_INVALID`

LanguageFeatures/Patterns/list_A04_t05.dart
Now the both cases work
```dart
Expect.equals("[1, 2, 3, 4, ...]", test1(<int>[1, 2, 3, 4, 5, 6]));
...
Expect.equals("default", test1([1, 2, 3, 4, 5, 6]));
```
=> Fixes #1764. Fix failing test

Language/Statements/Continue/label_t07.dart
No expected error on CFE. https://github.com/dart-lang/sdk/issues/51024
=> #1761. Issue number added

LanguageFeatures/Patterns/map_A04_t02.dart
=> Fixes #1742. Runtime errors fixed in map_A04_t02

Language/Classes/Instance_Methods/Operators/syntax_t01.dart, LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t05.dart, LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t06.dart, LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t07.dart, LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t12.dart, LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t13.dart, LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t14.dart, LanguageFeatures/Records/record_type_annotations_A01_t06.dart, LanguageFeatures/Set-literals/constant_set_literals_A02_t04.dart, LanguageFeatures/nnbd/weak/overriding/override_checking_A02_ARGS_t08.dart, LibTest/async/Timer/Timer_A01_t01.dart, LibTest/collection/LinkedList/toSet_A01_t01.dart, LibTest/core/List/remove_A01_t01.test.dart, LibTest/core/double/floorToDouble_A01_t01.dart, LibTest/core/double/floorToDouble_A01_t02.dart, LibTest/io/FileSystemEntity/identicalSync_A01_t03.dart
Please note the change of `operator operator`.
=> Remove superfluous words.

LanguageFeatures/Patterns/variable_A02_t03.dart, LanguageFeatures/Patterns/variable_A02_t04.dart, LanguageFeatures/Patterns/variable_A02_t05.dart, LanguageFeatures/Patterns/variable_A02_t06.dart, LibTest/async/StreamTransformer/StreamTransformer_A02_t02.dart
=> Remove superfluous `the`.

LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t01.dart, LanguageFeatures/Patterns/execution_pattern_for_in_statement_A01_t01.dart
These tests had a few mistakes that weren't noticed due to problems in the implementation.
https://dart-review.googlesource.com/c/sdk/+/290347 fixes those implementation problems, revealing the test mistakes.
=> Minor fixes to execution_pattern_for_in_{element,statement}_A01_t01

LanguageFeatures/nnbd/weak/overriding/override_checking_A01_opted_in_lib.dart
This simple change enables a large bunch of tests to work with class modifiers.
=> #1874. Update LanguageFeatures/nnbd/weak/overriding tests to work with class modifiers

LanguageFeatures/Class-modifiers/syntax_abstract_base_class_A01_t02.dart, LanguageFeatures/Class-modifiers/syntax_abstract_base_mixin_class_A01_t02.dart, LanguageFeatures/Class-modifiers/syntax_abstract_class_A01_t02.dart, LanguageFeatures/Class-modifiers/syntax_abstract_final_class_A01_t02.dart, LanguageFeatures/Class-modifiers/syntax_abstract_interface_class_A01_t02.dart, LanguageFeatures/Class-modifiers/syntax_abstract_mixin_class_A01_t02.dart, LanguageFeatures/Class-modifiers/syntax_sealed_class_A01_t02.dart
=> #1952. Constructor of classes that cannot be constructed cannot be torn off

Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A01_t01.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A01_t02.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A01_t03.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A01_t04.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A02_t01.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A02_t02.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A02_t03.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A02_t04.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t01.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t02.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t03.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t04.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t05.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t06.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t07.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t08.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t09.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t10.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t11.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t12.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t13.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t14.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t15.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t16.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t17.dart, Language/Interfaces/Correct_Member_Overrides/correct_member_overrides_A03_t18.dart
This is the first part of the tests.The second part will contain tests for setters and for default values of a function parameters
=> #2080. Add correct member overrides tests. Part 1.

LanguageFeatures/Inline-classes/static_analysis_member_invocation_A01_t01.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A02_t01.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A03_t01.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A04_t01.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A05_t01.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A05_t02.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A05_t03.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A06_t01.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A06_t02.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A06_t03.dart, LanguageFeatures/Inline-classes/static_analysis_member_invocation_A07_t01.dart
Move and rename these tests in the next PR
=> #2142. Change static analysis member invocation tests to be extension type tests

Language/Statements/Local_Variable_Declaration/default_initializer_t01.dart, Language/Statements/Local_Variable_Declaration/executing_t01.dart, Language/Statements/Local_Variable_Declaration/executing_t02.dart, Language/Statements/Local_Variable_Declaration/syntax_t01.dart, Language/Statements/Local_Variable_Declaration/syntax_t02.dart, Language/Statements/Local_Variable_Declaration/syntax_t03.dart, Language/Statements/Local_Variable_Declaration/syntax_t04.dart, Language/Statements/Local_Variable_Declaration/syntax_t05.dart, Language/Statements/Local_Variable_Declaration/syntax_t06.dart, Language/Statements/Local_Variable_Declaration/syntax_t07.dart, Language/Statements/Local_Variable_Declaration/syntax_t08.dart, Language/Statements/Local_Variable_Declaration/syntax_t11.dart, Language/Statements/Local_Variable_Declaration/syntax_t12.dart, Language/Statements/Local_Variable_Declaration/syntax_t13.dart, Language/Statements/Local_Variable_Declaration/syntax_t14.dart, Language/Statements/Local_Variable_Declaration/syntax_t15.dart
There will be two more PRs. Ther next one will rename the tests according to the updated assertions and delete duplicates. Another one will add missing tests
=> #2145. Update assertions and descriptions in the current Local variable declaration tests

LanguageFeatures/Extension-types/promotion_A01_t01.dart
Test for promotion of a private representation variable will be added to `LanguageFeatures/Private-fields-promotion`
=> #1400. Add promotion of a representation variable test

LanguageFeatures/Extension-types/syntax_A08_t04.dart
This test fails in CFE. https://github.com/dart-lang/sdk/issues/53467
=> #1400. Extension type. Add late instance variable test

Language/Expressions/Constants/constant_list_t03.dart, Language/Expressions/Constants/constant_map_t03.dart
Go on adding co19 regressions tests for issues discovered by @parlough
=> Fixes #2344. Add more tests for constants

LanguageFeatures/Enhanced-Enum/constructor_call_A01_t01.dart, LanguageFeatures/Enhanced-Enum/constructor_call_A01_t02.dart, LanguageFeatures/Enhanced-Enum/constructor_call_A02_t01.dart, LanguageFeatures/Enhanced-Enum/constructor_call_A02_t02.dart, LanguageFeatures/Enhanced-Enum/constructor_call_A03_t01.dart, LanguageFeatures/Enhanced-Enum/constructor_call_A03_t02.dart, LanguageFeatures/Enhanced-Enum/grammar_A05_t01.dart, LanguageFeatures/Enhanced-Enum/grammar_A05_t02.dart, LanguageFeatures/Enhanced-Enum/grammar_A05_t03.dart, LanguageFeatures/Enhanced-Enum/grammar_A11_t01.dart, LanguageFeatures/Enhanced-Enum/grammar_A12_t01.dart
Tests like ones, mentioned in https://github.com/dart-lang/language/issues/3460 are not added  because https://github.com/dart-lang/language/pull/3461 is not landed yet. They will be added after the landing
=> #2371. Add missing enhanced enums tests, update assertions

LanguageFeatures/Extension-types/exhaustiveness_constant_A01_t01.dart, LanguageFeatures/Extension-types/exhaustiveness_constant_A02_t01.dart, LanguageFeatures/Extension-types/exhaustiveness_constant_A02_t02.dart, LanguageFeatures/Extension-types/exhaustiveness_list_A02_t01.dart, LanguageFeatures/Extension-types/exhaustiveness_list_A03_t01.dart, LanguageFeatures/Extension-types/exhaustiveness_list_A03_t02.dart, LanguageFeatures/Extension-types/exhaustiveness_list_A03_t03.dart, LanguageFeatures/Extension-types/exhaustiveness_list_A04_t01.dart, LanguageFeatures/Extension-types/exhaustiveness_list_A04_t02.dart, LanguageFeatures/Extension-types/exhaustiveness_list_A04_t03.dart, LanguageFeatures/Extension-types/exhaustiveness_list_A04_t04.dart, LanguageFeatures/Extension-types/exhaustiveness_null_assert_A01_t01.dart, LanguageFeatures/Extension-types/exhaustiveness_null_assert_A01_t02.dart
=> #2119. Add missing experimental flags

LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t04_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t09.dart, LanguageFeatures/Augmentation-libraries/augmenting_types_A06_t09_lib.dart
Implement revie recommendations made in #2583
=> #2559. Update augmenting libraries tests according #2583

LibTest/core/Symbol/Symbol_A01_t01.dart, LibTest/core/Symbol/Symbol_A01_t02.dart, LibTest/core/Symbol/Symbol_A02_t01.dart, LibTest/core/Symbol/Symbol_A02_t02.dart, LibTest/core/Symbol/Symbol_A02_t03.dart, LibTest/core/Symbol/Symbol_A03_t01.dart, LibTest/core/Symbol/Symbol_A03_t02.dart, LibTest/core/Symbol/Symbol_A04_t01.dart, LibTest/core/Symbol/Symbol_A05_t01.dart, LibTest/core/Symbol/Symbol_A06_t01.dart
Sync from https://dart-review.googlesource.com/c/sdk/+/361220.
=> Update Symbol tests documentation

LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t01.dart, LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t01_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t02.dart, LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t02_lib.dart
Forgot about operators. Now added
=> #2559. Add tests for operators

LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t01.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t01_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t02.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t02_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t03.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t03_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t04.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t04_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t05.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t05_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t07.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t07_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t08.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t08_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t09.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t09_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t10.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t10_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t12.dart, LanguageFeatures/Augmentation-libraries/augmenting_functions_A02_t12_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t04_lib.dart
Again, appropriate extension types tests will be added later in a separate PR
=> #2559. Add tests for `augmented()` expression

LanguageFeatures/Augmentation-libraries/augmenting_types_A07_t03.dart, LanguageFeatures/Augmentation-libraries/augmenting_types_A07_t03_lib.dart
The updated test passes in the analyzer
=> Fixes #2733. Expect errors reported on a merged class

LanguageFeatures/Augmentation-libraries/augmented_expression_A05_t12_lib.dart
=> Fixes #2756. Fix the new roll failures

LibTest/io/RandomAccessFile/writeByte_A01_t01.dart
Removed not thread-safe buffer from this test.
=> Fixes #2804. Remove excessive flaky code from writeByte_A01_t01.dart

LanguageFeatures/Patterns/constant_A01_t01.dart, LanguageFeatures/Patterns/constant_A02_t01.dart, LanguageFeatures/Patterns/constant_A02_t04.dart, LanguageFeatures/Patterns/constant_A02_t07.dart, LanguageFeatures/Patterns/constant_A02_t10.dart, LanguageFeatures/Patterns/constant_A02_t13.dart, LanguageFeatures/Patterns/constant_A02_t16.dart, LanguageFeatures/Patterns/pattern_context_A07_t01.dart
With this fix all of the tests mentioned in #2856 pass
=> Fixes #2856. Remove `unreachable_switch_default` warning

LanguageFeatures/Patterns/shared_case_scope_A02_t02.dart
=> Fixes #2872. Fix `unreachable_switch_case` warning in shared_case_scope_A02_t02.dart

LanguageFeatures/Extension-types/static_analysis_extension_types_A08_t11.dart
See https://github.com/dart-lang/sdk/issues/56405#issuecomment-2360724456
=> Fixes #2887. Fix border type in static_analysis_extension_types_A08_t11.dart

LanguageFeatures/Parts-with-imports/export_A02_t02_part1.dart
=> Fixes #2893. In case of ambiguous export don't expect an error on the first export

LanguageFeatures/Parts-with-imports/scope_A08_t01_part2.dart, LanguageFeatures/Parts-with-imports/scope_A08_t02.dart, LanguageFeatures/Parts-with-imports/scope_A08_t02_part1.dart, LanguageFeatures/Parts-with-imports/scope_A08_t02_part2.dart
=> Fixes #2892. Change expected errors positions.

LanguageFeatures/Parts-with-imports/grammar_A04_t01_part1.dart
=> Fixes #2907. Update expected errors positions in grammar_A04_t01_part1.dart

LanguageFeatures/Augmentation-libraries/augmenting_enum_values_A03_t04.dart
Many times I did this error in augmentation tests unintentionally but just found that we still have no appropriate test :)
=> #2559. Add augmenting enum values test.

LanguageFeatures/Parts-with-imports/grammar_A04_t01.dart
=> Fixes #2926. Remove unnecessary error expectation from grammar_A04_t01.dart

TypeSystem/flow-analysis/reachability_A20_t01.dart, TypeSystem/flow-analysis/reachability_A20_t02.dart, TypeSystem/flow-analysis/reachability_A20_t03.dart, TypeSystem/flow-analysis/reachability_A20_t04.dart, TypeSystem/flow-analysis/reachability_A20_t05.dart
If these tests are ok, then I'll add the similar tests for other operators with two operands.
=> #3057. Add reachability tests for operator +

Language/Expressions/Unary_Expressions/variable_decrement_t01.dart, Language/Expressions/Unary_Expressions/variable_decrement_t02.dart, Language/Expressions/Unary_Expressions/variable_decrement_t03.dart, Language/Expressions/Unary_Expressions/variable_increment_t01.dart, Language/Expressions/Unary_Expressions/variable_increment_t02.dart, Language/Expressions/Unary_Expressions/variable_increment_t03.dart
This issue was already reviewed, approved and merged but in a wrong branch. This is PR to the main branch
=> Fixes #3049. Add more tests for unary prefix ++ and -- operators.

TypeSystem/flow-analysis/reachability_A01_t26.dart, TypeSystem/flow-analysis/reachability_A02_t01.dart, TypeSystem/flow-analysis/reachability_A02_t02.dart, TypeSystem/flow-analysis/reachability_A02_t03.dart, TypeSystem/flow-analysis/reachability_A02_t04.dart, TypeSystem/flow-analysis/reachability_A02_t05.dart, TypeSystem/flow-analysis/reachability_A03_t01.dart, TypeSystem/flow-analysis/reachability_A03_t02.dart, TypeSystem/flow-analysis/reachability_A03_t03.dart, TypeSystem/flow-analysis/reachability_A03_t04.dart, TypeSystem/flow-analysis/reachability_A03_t05.dart
Also added for-in tests for the type `Never`.
=> #3057. Add more reachability tests for `true` and `false` literals

TypeSystem/flow-analysis/definite_assignment_A05_t03.dart
Updated according to the https://github.com/dart-lang/sdk/issues/60322#issuecomment-2740949956
=> #3057. Update expectations for `while(false) ...` test

LanguageFeatures/Augmentation-libraries/augmenting_declarations_A05_t01.dart, LanguageFeatures/Augmentation-libraries/augmenting_declarations_A05_t01_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_declarations_A05_t02.dart, LanguageFeatures/Augmentation-libraries/augmenting_declarations_A05_t02_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_declarations_A05_t03.dart, LanguageFeatures/Augmentation-libraries/augmenting_declarations_A05_t03_lib.dart, LanguageFeatures/Augmentation-libraries/augmenting_declarations_A05_t04.dart, LanguageFeatures/Augmentation-libraries/augmenting_declarations_A05_t04_lib.dart, TypeSystem/flow-analysis/promotion_via_type_test_A03_t09.dart
Updated assertions and experimental flags only.
=> #3182. Update augmenting_declarations_A05_*.dart

TypeSystem/flow-analysis/promotion_switch_A05_t03.dart
The test updated according to the https://github.com/dart-lang/sdk/issues/60708#issuecomment-2887677566
=> #3057. Update promotion_switch_A05_t03.dart according to the current implementation

LanguageFeatures/Augmentation-libraries/application_order_A01_t03_lib1.dart, LanguageFeatures/Augmentation-libraries/application_order_A01_t03_lib2.dart, LanguageFeatures/Augmentation-libraries/application_order_A01_t03_lib3.dart
Updated test passes in analyzer and CFE.
=> Fixes #3332. Add more expected errors in application_order_A01_t03
