- WebPlatformTest/shadow-dom/testcommon.dart
dart:mirrors seems to be unused.
Since mirrors are unsupported in the fast-startup emitter and usually slow down compilation I removed it.
> Remove 'dart:mirrors' import.

- Utils/async_utils.dart
A generic function with a type parameter has to have the type parameter listed in angle brackets after the function name.
> Fix generic function syntax in async_utils

- LibTest/io/RandomAccessFile/close_A01_t01.dart
- LibTest/io/RandomAccessFile/close_A01_t02.dart
This PR updates co19 tests for https://github.com/dart-lang/sdk/issues/32015.
CL for the core libraries: https://dart-review.googlesource.com/c/sdk/+/44060.
If it's already possible, `Future` should probably be changed to `Future<void>`.
> Update tests for RandomAccessFile.close

- LibTest/io/sleep/sleep_A01_t01.dart
This test flaked once. I am unable to reproduce it on my macbook. The only reason we could come up with is rounding imprecision. In order to ensure that future flakes are not due to rounding, add a one millisecond margin to the check.
```dart
FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/sleep/sleep_A01_t01
Expected: Pass
Actual: RuntimeError
--- Command "vm_compile_to_kernel" (took 01.000025s):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_sleep_sleep_A01_t01/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/sleep/sleep_A01_t01.dart --packages=/b/s/w/ir/.packages …
```
> sleep test time 1 millisecond avoid rounding errors

- LibTest/io/File/openRead_A02_t01.dart
Test was rewrittent to test that returned stream can be listened to
> Wrong File.openRead() test rewritten

- LibTest/io/Stdin/test.lib.dart
After commit 365808e85, the entire sandbox directory is deleted,
but there's still a separate attempt to delete the temp file
created by the test asynchronously as well. If the file deletion
ends up happening after the sandbox is deleted, then we get a
spurious runtime error.
Fixes #212.
> Remove now-redundant file delete.

- LayoutTests/fast/css-generated-content/pseudo-animation_t01.dart
This test was timing out because window.onLoad was not triggering after a listener was added.
Also, addEventListener is preferred to onLoad = , because it does not overwrite a previous handler.
> Fix wait for window.onLoad event

- LibTest/io/Datagram/Datagram_A01_t01.dart
- LibTest/io/Datagram/Datagram_A01_t02.dart
- LibTest/io/Datagram/address_A01_t01.dart
- LibTest/io/Datagram/data_A01_t01.dart
- LibTest/io/Datagram/port_A01_t01.dart
This is in preparation for Datagram requiring a
Uint8List passed to its constructor. This is a
forward-compatible change.
dart-lang/sdk#36900
dart-lang/co19#381
> Pass Uint8List to Datagram

- LibTest/io/Datagram/data_A01_t01.dart
- LibTest/io/HttpClientResponse/redirect_A05_t03.dart
- LibTest/io/HttpClientResponse/redirects_A03_t01.dart
There were a few places where `.cast<List<int>>()` calls were
missed in #384 and #385, and likewise for `Datagram.data` in #382.
Note that I had to change one of the tests of `Datagram.data`, since
the existing test was setting invalid values as the data (signed
integers or integers that didn't fit in 8-bytes).
dart-lang/sdk#36900
https://github.com/dart-lang/co19/issues/381
https://github.com/dart-lang/co19/issues/383
> Fix a few remaining call-sites

- LibTest/core/Uri/decodeComponent_A01_t02.dart
It is not legal to encode surrogates in UTF-8. This has so far been possible, but this is likely [going away](https://github.com/dart-lang/sdk/issues/41100). Thus, tests should not do it.
> Skip surrogates in decode test

- LibTest/isolate/Isolate/kill_A01_t04.dart
@aam please review. Does this test do what you want?
> Fixes #1004. Add tests that confirms that tight-looped isolate is not killed with Isolate.beforeNextEvent priority

- LanguageFeatures/Enhanced-Enum/grammar_A10_t04.dart
We had a discussion with Erik about the static `values` setter in enums, and the conclusion is that they should be allowed. This PR adjusts a test accordingly.
> Correct an enhanced-enum test to allow setters named values

- LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t06.dart
- LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t07.dart
- LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t15.dart
- LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t16.dart
- LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t20.dart
- LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t24.dart
- LanguageFeatures/Enhanced-Enum/implementing_enum_A04_t27.dart
Just a few typo-level changes to the new co19 tests.
> Fixes needed based on roll f5124538

- LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A02_t02.dart
- LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_A04_t11.dart
Add missing invocations of `attachToFinalizer1` and `attachToFinalizer` to LanguageFeatures/FinalizationRegistry/ffi/Finalizer/attach_*.dart.
> Added invocation of functions doing attach

- LanguageFeatures/Super-parameters/grammar_A02_t01.dart
The code of the test contains a field that isn't required for the purpose of the test, and yet it causes an additional compile-time error because it is uninitialized and non-nullable.
> Remove unused and uninitialized non-nullable field from a test

- LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t01.dart
- LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t04.dart
- LanguageFeatures/Enhanced-Enum/implementing_enum_A01_t06.dart
This PR adds expected errors that the CFE reports on concrete members named `index` in implementers of the `Enum` interface. The discrepancy between the CFE and the Analyzer in this case is that the Analyzer doesn't report the error on `index` if the implementer is concrete and, therefore, already erroneous.
> Add expected CFE errors on concrete 'index' members

- LibTest/collection/HashSet/inherited_tests.lib.dart
- LibTest/core/Iterable/allTests.lib.dart
- LibTest/core/Set/all_tests.lib.dart
`co19` version. For `co19_2` see https://github.com/dart-lang/co19/pull/1475
> #1430. For HasSet don't run tests that checks iteration order 

- LanguageFeatures/Records/interaction_with_legacy_A01_t01.dart
- LanguageFeatures/Records/interaction_with_legacy_A02_t01.dart
- LanguageFeatures/Records/interaction_with_legacy_A03_t01.dart
- LanguageFeatures/Records/interaction_with_legacy_A04_t01.dart
- LanguageFeatures/Records/interaction_with_legacy_A04_t02.dart
- LanguageFeatures/Records/interaction_with_legacy_A04_t03.dart
- LanguageFeatures/Records/interaction_with_legacy_A04_t04.dart
You cannot have 
```dart
// @dart = 2.18
// SharedOptions=--enable-experiment=records
```
in the same library
> Fixes #1511. [Records] Remove `records` experimental flag from legacy libraries

- Utils/async_utils.dart
The dart2wasm compiler does not support `Function.apply` and may not do so in the foreseeable future. For this reason, we should avoid using `Function.apply` outside of code that specifically tests `Function.apply`.
> Avoid Function.apply in utility code

- LibTest/html/Element/isContentEditable_A01_t01.dart
I'm unable to test this fix. But, I believe that it may help. Safari has the `user-select` CSS setting as `none` by default. This fix enables it. Probably, the test is flaky because Safary has different settings on differenf bots. Where this setting is enabled the test completes succesfully, where not it fails.
@athomas is there a way to test this PR?
> Fixes #959. Fix flaky test. Enable user-select for Safari

- Language/Statements/Continue/label_t07.dart
There is an incoming change to add a new diagnostic for both the analyzer and the front end.
Related to https://github.com/dart-lang/sdk/issues/49852
I think this should be merged once the [breaking change request](https://github.com/dart-lang/sdk/issues/50902) is accepted.
> Update test for the new `CONTINUE_LABEL_INVALID`

- LanguageFeatures/Patterns/object_A07_t05.dart
- LanguageFeatures/Patterns/object_A07_t06.dart
See https://github.com/dart-lang/language/issues/2745
> #1401. [Patterns] Object pattern test added

- LanguageFeatures/Constant-update-2018/ShortCircuitOperators_A01_t08.dart
- LanguageFeatures/nnbd/weak/null_aware_operator_A02_t01.dart
- LanguageFeatures/nnbd/weak/null_aware_operator_A05_t02.dart
- LanguageFeatures/nnbd/weak/type-normalization/equations_A05_t01.dart
Another point, sometimes the year is `2020` and sometimes is it `2011-2017`, I guess it should be unified to have a single year instead of a range, as this is the majority of cases.
> Fix year in header

- LanguageFeatures/Patterns/null_assert_A03_t01.dart
- LanguageFeatures/Patterns/null_check_A02_t01.dart
`case v3!:` are still present but we don't expect a warning there. If there will be one the test fail
> #1401. [Patterns]. Added tests, expecting warnings in case of unnecessary null check/assert pattern

- LanguageFeatures/Records/interaction_with_legacy_A01_lib.dart
- LanguageFeatures/Records/interaction_with_legacy_A01_t01.dart
See https://github.com/dart-lang/language/commit/8c8d93b8b6e776f3f2360cde5039c433f7efaeab
> #1399. [Records] Allow legacy libraries that don't support records be able to see the Record class

- LanguageFeatures/Patterns/execution_pattern_for_element_A01_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_element_A01_t02.dart
- LanguageFeatures/Patterns/execution_pattern_for_element_A01_t03.dart
- LanguageFeatures/Patterns/execution_pattern_for_element_A01_t04.dart
- LanguageFeatures/Patterns/execution_pattern_for_element_A01_t05.dart
- LanguageFeatures/Patterns/execution_pattern_for_element_A02_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_statement_A01_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_statement_A01_t02.dart
- LanguageFeatures/Patterns/execution_pattern_for_statement_A01_t03.dart
- LanguageFeatures/Patterns/execution_pattern_for_statement_A01_t04.dart
- LanguageFeatures/Patterns/execution_pattern_for_statement_A01_t05.dart
- LanguageFeatures/Patterns/execution_pattern_for_statement_A02_t01.dart
- LanguageFeatures/Patterns/execution_switch_expression_A01_t01.dart
- LanguageFeatures/Patterns/execution_switch_expression_A02_t01.dart
Pattern-for element tests here check `List` only. Let's review it first, then I'll add tests for `Map` and `Set`
> #1401. Execution of pattern-for statement and element. Switch expression

- LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t02.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t03.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_element_A01_t04.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_element_A02_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_element_A03_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_element_A04_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_statement_A01_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_statement_A01_t02.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_statement_A01_t03.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_statement_A01_t04.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_statement_A02_t01.dart
- LanguageFeatures/Patterns/execution_pattern_for_in_statement_A03_t01.dart
Please note the following.
1. Tests for for-in-element are written for `List` only. Please review them first and I'll then add the similar tests for `Map` and `Set`
2. Some tests check both static and dynamic semantic. I believe it's Ok if type check is part of the runtime semantics and it uses inferred types. 
3. We also need tests for async for-in loop. I'll add them in a separate PR. Again, let's review this one first
> #1401. Pattern-for-in statement and element tests

- LanguageFeatures/Patterns/matching_list_A01_t01.dart
- LanguageFeatures/Patterns/matching_list_A01_t02.dart
- LanguageFeatures/Patterns/matching_list_A02_t01.dart
- LanguageFeatures/Patterns/matching_list_A02_t02.dart
- LanguageFeatures/Patterns/matching_list_A02_t03.dart
- LanguageFeatures/Patterns/matching_list_A02_t04.dart
- LanguageFeatures/Patterns/matching_list_A03_t01.dart
- LanguageFeatures/Patterns/matching_list_A03_t02.dart
- LanguageFeatures/Patterns/matching_list_A03_t03.dart
- LanguageFeatures/Patterns/matching_list_A04_t01.dart
- LanguageFeatures/Patterns/matching_list_A04_t02.dart
- LanguageFeatures/Patterns/matching_list_A04_t03.dart
- LanguageFeatures/Patterns/matching_list_A04_t04.dart
- LanguageFeatures/Patterns/matching_list_A05_t01.dart
- LanguageFeatures/Patterns/matching_list_A05_t02.dart
- LanguageFeatures/Patterns/matching_list_A05_t03.dart
- LanguageFeatures/Patterns/matching_parenthesized_A01_t01.dart
- LanguageFeatures/Patterns/matching_parenthesized_A02_t01.dart
- LanguageFeatures/Patterns/patterns_collections_lib.dart
Please note `matching_list_A04_t04.dart`. It checks the following [informal statement](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#matching-refuting-and-destructuring:~:text=If%20there%20is%20a%20non%2Dmatching%20rest%20element%2C%20the%20unneeded%20list%20elements%20are%20completely%20skipped%20and%20we%20don%27t%20even%20call%20sublist()%20to%20access%20them.)
> If there is a non-matching rest element, the unneeded list elements are completely skipped and we don't even call sublist() to access them.
Probably it's too strong to test that `sublist()` is not called in this case. "We don't call" doesn't necessary mean "we shouldn't call". Probably, it's not an error for some implementations to call `sublist()` for some …
> #1401. Matching tests for list pattern

- LanguageFeatures/Set-literals/exact_types_of_literals_A01_t01.dart
I don't see any other ways how to fix this
> Fixes #1937. Add `@dart=2.19` to class implementing `LinkedHashSet`

- LanguageFeatures/Patterns/pattern_context_A01_t01.dart
Updated test is not failing on CFE
> Fixes #2008. Split pattern_context_A01_t01.dart test to multiple methods

- LanguageFeatures/nnbd/weak/const_evaluation_A06_t01.dart
This test used to test a strong mode. Now in a weak mode it fails. As far as I understand here we have class
```dart
class C<T> {
final T x;
const C.t(Object? o, T t) : x = o as T;
}
```
When we call
```dart
const c1 = C.t(null, cLegacyInt);
```
`T` is inferred as `int*`. `int*` became `int` and `x = o as int;` failed. But now in a weak mode is doesn't throw, so we should expect no error
> Fixes #2059. Don't expect an error in a weak mode

- LanguageFeatures/nnbd/weak/const_evaluation_A06_t01.dart
I'm not sure if it makes sense to preserve `Expect.isNull()` here. But, probably, there are some VM configurations can be run if there is no expected CFE error
> Fixes #2061. Add expected analyzer error to const_evaluation_A06_t01.dart

- LanguageFeatures/Inline-classes/composing_inline_classes_A05_t06.dart
Noticed that this wes missed. We have tests for `inline class C implements I1, I2 {...}` where `I1` and `I2` both have member `m` with same or dirrerent signatures and `C` has or has no redeclaration of `m`. But have no tests for the case when `C` has only one superinterface and overrides member `m` in the way which is not correct for reular classes
> #1400. Add inline classes members override test

- Language/Classes/definition_t01.dart
- Language/Classes/definition_t23.dart
- Language/Classes/mixins_t01.dart
- Language/Classes/mixins_t02.dart
- Language/Expressions/Lookup/Getter_and_Setter_Lookup/definition_t08.dart
- Language/Expressions/Lookup/Method_Lookup/instance_t03.dart
- Language/Expressions/Lookup/Method_Lookup/superclass_t09.dart
- Language/Expressions/Method_Invocation/Ordinary_Invocation/accessible_instance_member_t07.dart
- Language/Expressions/Method_Invocation/Ordinary_Invocation/accessible_instance_member_t08.dart
- Language/Expressions/Property_Extraction/Super_Getter_Access_and_Method_Closurization/method_extraction_t03.dart
- Language/Generics/Superbounded_types/class_A04_t03.dart
- Language/Types/Interface_Types/direct_supertype_t04.dart
- Language/Types/Interface_Types/direct_supertype_t05.dart
- LanguageFeatures/Super-mixins/implementation_t07.dart
- LanguageFeatures/Super-mixins/implementation_t08.dart
- LanguageFeatures/Super-mixins/mixin_application_t05.dart
- LanguageFeatures/Super-mixins/mixin_application_t06.dart
- LanguageFeatures/Super-mixins/mixin_application_t11.dart
- LanguageFeatures/Super-mixins/mixin_application_t12.dart
- LanguageFeatures/Super-mixins/super_invocation_t03.dart
- LanguageFeatures/Super-mixins/super_invocation_t06.dart
- LanguageFeatures/Super-mixins/super_invocation_t09.dart
- LanguageFeatures/Super-mixins/super_invocation_t12.dart
- LanguageFeatures/Super-mixins/super_invocation_t15.dart
- LanguageFeatures/Super-mixins/super_invocation_t18.dart
- LanguageFeatures/nnbd/weak/import_legacy_lib_A01_t09.dart
- LanguageFeatures/nnbd/weak/overriding/override_checking_A01_opted_in_futureor_lib.dart
Main part of the changes is to remove `// @dart=2.19` and to replace `class` by `mixin class` where necessary
> #2094. Remove mixin-related TODO and @dart=2.19

- Language/Classes/Instance_Methods/covariant_A01_t02.dart
- Language/Classes/Instance_Methods/covariant_A01_t03.dart
- Language/Classes/Instance_Methods/covariant_A01_t04.dart
- Language/Classes/Instance_Methods/covariant_A01_t07.dart
- Language/Classes/Instance_Methods/covariant_A01_t08.dart
- Language/Classes/Instance_Methods/covariant_A01_t09.dart
- Language/Classes/Instance_Methods/covariant_A01_t10.dart
- Language/Classes/Instance_Methods/covariant_A01_t11.dart
- Language/Classes/Instance_Methods/covariant_A01_t12.dart
- Language/Classes/Instance_Methods/covariant_A01_t13.dart
- Language/Classes/Instance_Methods/covariant_A01_t14.dart
- Language/Classes/Instance_Methods/covariant_A01_t15.dart
- Language/Classes/Instance_Methods/covariant_A01_t16.dart
- Language/Classes/Instance_Methods/covariant_A01_t17.dart
- Language/Classes/Instance_Methods/covariant_A01_t18.dart
- Language/Classes/Instance_Methods/covariant_A01_t19.dart
- Language/Classes/Instance_Methods/covariant_A01_t20.dart
Github shows doens of changes, but in fact, this is renaming of existing tests only. No any other changes, just renaming
> Fixes #2087. Reorder covariance tests to make maintenance easier

- LanguageFeatures/Inline-classes/dynamic_semantics_inline_class_A01_t01.dart
- LanguageFeatures/Inline-classes/dynamic_semantics_inline_class_A02_t01.dart
- LanguageFeatures/Inline-classes/dynamic_semantics_inline_class_A03_t01.dart
- LanguageFeatures/Inline-classes/dynamic_semantics_inline_class_A03_t02.dart
- LanguageFeatures/Inline-classes/dynamic_semantics_inline_class_A04_t01.dart
- LanguageFeatures/Inline-classes/dynamic_semantics_inline_class_A05_t01.dart
This also fixes https://github.com/dart-lang/co19/issues/2169
> #2142. Change dynamic semantics inline class tests to be extension type tests

- LanguageFeatures/Extension-types/upper_bound_A01_t01.dart
- LanguageFeatures/Extension-types/upper_bound_A01_t02.dart
- LanguageFeatures/Extension-types/upper_bound_A01_t03.dart
- LanguageFeatures/Extension-types/upper_bound_A01_t04.dart
- LanguageFeatures/Extension-types/upper_bound_A01_t05.dart
- LanguageFeatures/Extension-types/upper_bound_A01_t06.dart
@eernstg if you believe that we need more tests, please let me know
> #2217. Add tests for calculating of the least upper bound for extension types

- LanguageFeatures/Subtyping/dynamic/generated/extension_type_arguments_binding_A10_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_arguments_binding_A10_t02.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_arguments_binding_A10_t03.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_class_member_A10_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_class_member_A10_t02.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_class_member_A10_t03.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_global_variable_A10_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_local_variable_A10_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_return_value_A09_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_return_value_A10_t01.dart
- LanguageFeatures/Subtyping/dynamic/test_types/extension_type_A09.dart
- LanguageFeatures/Subtyping/dynamic/test_types/extension_type_A10.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_arguments_binding_A08_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_arguments_binding_A08_t02.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_arguments_binding_A08_t03.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_class_member_A08_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_class_member_A08_t02.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_class_member_A08_t03.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_global_variable_A08_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_local_variable_A08_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_return_value_A08_t01.dart
There were two tests with the same name.
```
LanguageFeatures/Subtyping/test_types/extension_type_A08.dart
LanguageFeatures/Subtyping/dynamic/test_types/extension_type_A08.dart
```
Generator resolves this conflict by adding `_1_` suffix to the filename. But these suffixed tests were forgotten to add to git. This PR renames tests to avoid name conflict and adds missing generated tests
> #1400. Extension types subtyping tests. Resolve name conflict, add missing tests

- LanguageFeatures/Private-fields-promotion/promotion_A01_t01.dart
- LanguageFeatures/Private-fields-promotion/promotion_A01_t02.dart
- LanguageFeatures/Private-fields-promotion/promotion_A01_t03.dart
- LanguageFeatures/Private-fields-promotion/promotion_A01_t04.dart
- LanguageFeatures/Private-fields-promotion/promotion_A01_t05.dart
- LanguageFeatures/Private-fields-promotion/promotion_A02_t01.dart
- LanguageFeatures/Private-fields-promotion/promotion_A02_t02.dart
- LanguageFeatures/Private-fields-promotion/promotion_A02_t03.dart
- LanguageFeatures/Private-fields-promotion/promotion_A02_t04.dart
- LanguageFeatures/Private-fields-promotion/promotion_A03_t01.dart
- LanguageFeatures/Private-fields-promotion/promotion_A03_t02.dart
- LanguageFeatures/Private-fields-promotion/promotion_A04_t01.dart
- LanguageFeatures/Private-fields-promotion/promotion_A04_t02.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t01.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t02.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t03.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t04.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t05.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t06.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t07.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t08.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t09.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t10.dart
- LanguageFeatures/Private-fields-promotion/promotion_A05_t10.lib.dart
- LanguageFeatures/Private-fields-promotion/promotion_A06_t01.dart
- LanguageFeatures/Private-fields-promotion/promotion_A06_t02.dart
- LanguageFeatures/Private-fields-promotion/promotion_A06_t03.dart
- LanguageFeatures/Private-fields-promotion/promotion_A06_t04.dart
- LanguageFeatures/Private-fields-promotion/promotion_A07_t01.dart
- LanguageFeatures/Private-fields-promotion/promotion_A07_t02.dart
There going to be two more changes.
- Rename and reorder existing tests according to the new assertion text
- Add new tests
> #2258. Update assertions of private fields promotion tests. Add new ones

- LibTest/io/Stdin/readByteSync_A02_t01.dart
Thanks to @mraleph for helping with it!
> Fixes #970. Don't use Process.kill() to exit a process

- LibTest/io/WebSocket/closeCode_A01_t02.dart
Updated test is not racy any longer
> Fixes #2268. Fix LibTest/io/WebSocket/closeCode_A01_t02.dart to be not racy

- LibTest/io/Link/create_A04_t07.dart
- LibTest/io/Link/create_A04_t08.dart
- LibTest/io/Link/create_A04_t09.dart
- LibTest/io/Link/create_A04_t10.dart
- LibTest/io/Link/create_A04_t11.dart
- LibTest/io/Link/create_A04_t12.dart
- LibTest/io/Link/create_A04_t13.dart
- LibTest/io/Link/create_A04_t14.dart
- LibTest/io/Link/create_A04_t15.dart
- LibTest/io/Link/create_A04_t16.dart
Tests written according to the https://github.com/dart-lang/sdk/issues/53684
On Windows invalid `Link` reports itself as `FileSystemEntityType.link`  (`FileSystemEntityType.notFound` on other platforms). Also, on Windows, Link created as link pointing to a directory cannot point to a file and vice versa
> #2291. Update `Link.create()` according to the documentation. Part 2

- LibTest/io/RawDatagramSocket/receive_A02_t01.dart
@brianquinlan seems that maximum size of 65503 exists on MacOS only. See https://dart-current-results.web.app/#/filter=co19/LibTest/io/RawDatagramSocket/receive_A02_t02. But I didn't find any specification confirming that. So, I preserved the test which confirms that 65503 bytes can be received and deleted the one checking what's going on when UDP size is more than 65503
> Fixes #2323. Don't test datagram size more than 65503

- LanguageFeatures/Extension-types/dynamic_semantics_extension_type_A03_t02.dart
- LanguageFeatures/Extension-types/nullability_A02_t01.dart
- LanguageFeatures/Extension-types/static_analysis_extension_types_A17_t01.dart
- LanguageFeatures/Extension-types/upper_bound_A01_t03.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_arguments_binding_A02_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_arguments_binding_A02_t02.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_arguments_binding_A02_t03.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_class_member_A02_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_class_member_A02_t02.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_class_member_A02_t03.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_global_variable_A02_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_local_variable_A02_t01.dart
- LanguageFeatures/Subtyping/dynamic/generated/extension_type_return_value_A02_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_arguments_binding_A02_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_arguments_binding_A02_t02.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_arguments_binding_A02_t03.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_class_member_A02_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_class_member_A02_t02.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_class_member_A02_t03.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_global_variable_A02_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_local_variable_A02_t01.dart
- LanguageFeatures/Subtyping/static/generated/extension_type_return_value_A02_t01.dart
- LanguageFeatures/Subtyping/test_types/extension_type_A02.dart
This PR contains not all of the tests mentioned in #2359. It contains only the tests that can be updated to not fail with both old and new nullability rules. So, they won't break anything and can be merged safely. 
Other tests will be fixed after the landing of the https://dart-review.googlesource.com/c/sdk/+/333500
> #2359. Update tests according to the new nullability rules. Part 1

- LanguageFeatures/Extension-methods/syntax_t07.dart
We have an interesting case here. 
Without `// SharedOptions=--enable-experiment=inline-class`  experimental flag  `extension type on (int i,)` should be treated as an `extension` named `type` on record type `(int,)`.
With  `// SharedOptions=--enable-experiment=inline-class` it became an extension type with a excesive comma after the representation type.
So, we may have two tests here
```dart
extension type on 
//        ^^^^
// [analyzer] unspecified
// [cfe] unspecified
(int i,) {}
```
And
```dart
// SharedOptions=--enable-experiment=inline-class
extension type on
(int i,) {}
//        ^
// [analyzer] unspecified
// [cfe] unspecified
```
But the first one became an invalid when the extension types will stop to be an experiment but became the part of the language. So I added only the one …
> #2339. Add test for extension named type and a record type

- LanguageFeatures/Extension-types/dynamic_semantics_extension_type_A03_t02.dart
- LanguageFeatures/Extension-types/upper_bound_A01_t05.dart
- LanguageFeatures/Extension-types/upper_bound_A01_t06.dart
Please, don't merge this PR until landing of https://github.com/dart-lang/language/pull/3434
> #2359. Fix existing extension types tests according to the new nullability rules

- LanguageFeatures/Extension-types/type_inference_A01_t01.dart
- LanguageFeatures/Extension-types/type_inference_A01_t02.dart
There is no statement from the assertion in the spec but I think it is assumed
> #1400. Add type inference tests for extension types

- LanguageFeatures/Extension-types/static_analysis_extension_types_A10_t16.dart
Please note that the statement in the assertion doesn't contain any mentions of type `Never` but I didn't found a better one in the spec. May be the type `Never` was just forgotten there?
> Fixes #2491. Add test that an extension type cannot implement type `Never`

- LanguageFeatures/Extension-types/static_analysis_extension_types_A20_t07.dart
- LanguageFeatures/Extension-types/static_analysis_extension_types_A20_t08.dart
Based on https://github.com/dart-lang/sdk/issues/54491
> #2477. Add more constant evaluation tests

- TypeSystem/type-variance/out_non_covariant_A01_t01.dart
- TypeSystem/type-variance/out_non_covariant_A01_t02.dart
- TypeSystem/type-variance/out_non_covariant_A01_t03.dart
- TypeSystem/type-variance/out_non_covariant_A01_t04.dart
- TypeSystem/type-variance/out_non_covariant_A01_t05.dart
- TypeSystem/type-variance/out_non_covariant_A01_t06.dart
Before switching to macroses just want to submit the current work
> #2548. Add tests for out parameter in a contrvariant position

- LanguageFeatures/Augmentation-libraries/defining_augmentation_A05_t01.dart
- LanguageFeatures/Augmentation-libraries/defining_augmentation_A05_t02.dart
- LanguageFeatures/Augmentation-libraries/defining_augmentation_A05_t02_lib.dart
Seems that in https://github.com/dart-lang/language/issues/3646 all agreed that it should be a compile-time error
> #2559. Add augmenting itself tests

- LanguageFeatures/Augmentation-libraries/augmenting_types_A04_t01.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A04_t01_lib.dart
This PR doesn't include test for augmenting unnamed extension (`augment extension {...}`). I'm expecting it to be a compile-time error. But probably a separate statement will be added for this case. Anyway I'll add an appropriate test later
> #2559. Add augmenting types tests. Part 5

- LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t01_lib2.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A01_t02_lib2.dart
Add enum values to avoid false-positive outcome because of missing values
> #2559. Make enum augmenting types tests stronger

- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t01.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t02.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t03.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t03_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t04.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t05.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t05_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t07.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t07_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t08.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t08_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t09.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t09_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t10.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t10_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t12.dart
- LanguageFeatures/Augmentation-libraries/augmenting_functions_A01_t12_lib.dart
This PR contains extensions as well. Taking into account https://github.com/dart-lang/language/pull/3701 I think it's safe now
> #2559. Add augmenting functions tests

- LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t03_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t05_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t08.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t08_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t09.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A01_t09_lib.dart
Added tests cases when `augmented` is called from some function
```dart
augment ... someGetter {
var f = () {
return augmented;
}
return f();
}
```
> #2559. Add more augmenting expression tests for getters

- LanguageFeatures/Extension-types/nullability_A01_t05.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_arguments_binding_A11_t01.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_arguments_binding_A11_t02.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_arguments_binding_A11_t03.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_class_member_A11_t01.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_class_member_A11_t02.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_class_member_A11_t03.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_global_variable_A11_t01.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_local_variable_A11_t01.dart
- TypeSystem/subtyping/dynamic/generated/extension_type_return_value_A11_t01.dart
- TypeSystem/subtyping/static/generated/extension_type_arguments_binding_A11_t01.dart
- TypeSystem/subtyping/static/generated/extension_type_arguments_binding_A11_t02.dart
- TypeSystem/subtyping/static/generated/extension_type_arguments_binding_A11_t03.dart
- TypeSystem/subtyping/static/generated/extension_type_class_member_A11_t01.dart
- TypeSystem/subtyping/static/generated/extension_type_class_member_A11_t02.dart
- TypeSystem/subtyping/static/generated/extension_type_class_member_A11_t03.dart
- TypeSystem/subtyping/static/generated/extension_type_global_variable_A11_t01.dart
- TypeSystem/subtyping/static/generated/extension_type_local_variable_A11_t01.dart
- TypeSystem/subtyping/static/generated/extension_type_return_value_A11_t01.dart
- TypeSystem/subtyping/test_types/extension_type_A11.dart
For subtyping tests it's enough to review `TypeSystem/subtyping/test_types/extension_type_A11.dart`. All other tests are generated ones
> Fixes #2624. Add more extension type tests for union types

- LanguageFeatures/Wildcards/binding_A03_t01.dart
- LanguageFeatures/Wildcards/binding_A03_t02.dart
- LanguageFeatures/Wildcards/binding_A03_t03.dart
Function parameters initializers must be constants therefore cannot be tested
> #2641. Add wildcard initializer tests

- LanguageFeatures/Wildcards/other_declarations_A05_t22.dart
- LanguageFeatures/Wildcards/other_declarations_A05_t23.dart
- LanguageFeatures/Wildcards/other_declarations_A05_t24.dart
- LanguageFeatures/Wildcards/other_declarations_A05_t25.dart
- LanguageFeatures/Wildcards/other_declarations_A05_t26.dart
- LanguageFeatures/Wildcards/other_declarations_A05_t27.dart
- LanguageFeatures/Wildcards/other_declarations_A05_t28.dart
- LanguageFeatures/Wildcards/other_declarations_A05_t29.dart
There are no "implements" tests because `enum E implements ContainsWildcardMethod` is an error itself without implementation of `_`
> #2641. Check that it is still an error to declare more than one enum member named `_`

- LanguageFeatures/Patterns/Exhaustiveness/exhaustiveness_sealed_A02_t04.dart
- LanguageFeatures/Patterns/Exhaustiveness/exhaustiveness_sealed_A02_t05.dart
The fix suggested in this comment https://github.com/dart-lang/sdk/issues/53392#issuecomment-2113062914  doesn’t work. Adding `{...}` doesn’t help, but reordering does.
It’s hard for me to explain why I preserved `i4` expecting no error. To me, it seems useful to have these issues somewhere in the tests. If, one day, someone fixes it (probably unintentionally), and flow analysis starts reporting an error for `i4` too, then the tests will fail, and the author will know that (s)he fixed it as well.
If you believe that it is not necessary, let me know, and I’ll remove it. At least there is no issue in real life. To make the code work, people have to fix all their issues, and eventually, the unreported ones become the first one and will be reported.
> Fixes #2668. Reorder switch expressions to avoid flow analysis secondary issues

- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t01.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t02.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t03.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t03_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t04.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t05.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A09_t05_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t01.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t02.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t03.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t03_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t04.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t05.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t05_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t06.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t06_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t07.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t07_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t08.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t08_lib.dart
Tests that renamed to `*_A10_*` check another statement in the spec. So they were renamed and assertion text updated. There will be more tests. We need tests for initializing expression, for example.
> #2559. Update assertion text and rename some tests

- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t03_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t05_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t06_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t08_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t09_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t10_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t11.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t11_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t12_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t13.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t13_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t14.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t14_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t15.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t15_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t16.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t16_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t17.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t17_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t18.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t18_lib.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t19.dart
- LanguageFeatures/Augmentation-libraries/augmented_expression_A10_t19_lib.dart
In case of enum `final f = () {...};` is not a constant exptession and therefore an error. Removed.
> #2559. Remove erroneous test cases, add more tests for augmented expression

- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t01.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t02.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t03.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t03_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t04.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t05.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t05_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t06.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t06_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t07.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t07_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t08.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t08_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t09.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t09_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t10.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t10_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t11.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t11_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t12.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t12_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t13.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t13_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t14.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t14_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t15.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A02_t15_lib.dart
This PR only updates assertions and descriptions for `augmenting_types_A02_*.dart` tests.
> #2559. Update assertions in augmenting types tests.

- Language/Statements/Switch/execution_case_no_default_t01.dart
- Language/Statements/Switch/execution_case_t01.dart
- LanguageFeatures/Class-modifiers/syntax_abstract_base_mixin_class_A06_t01.dart
- LanguageFeatures/Class-modifiers/syntax_base_mixin_class_A05_t01.dart
- LanguageFeatures/Extension-types/exhaustiveness_variable_A04_t01.dart
- LanguageFeatures/Patterns/map_A08_t01.dart
- LanguageFeatures/Patterns/matching_list_A06_t01.dart
- LanguageFeatures/Patterns/null_assert_A03_t01.dart
- LanguageFeatures/Patterns/null_check_A02_t01.dart
- LanguageFeatures/Patterns/scope_A04_t01.dart
- LanguageFeatures/Patterns/shared_case_scope_A01_t01.dart
- LanguageFeatures/Patterns/shared_case_scope_A01_t02.dart
- LanguageFeatures/Patterns/shared_case_scope_A01_t03.dart
- LanguageFeatures/Patterns/switch_statement_A01_t01.dart
- LanguageFeatures/Patterns/variable_A03_t02.dart
- LanguageFeatures/Patterns/variable_A03_t03.dart
- LanguageFeatures/Patterns/variable_A03_t05.dart
The analyzer Hints are slowly, incrementally, being migrated to being Warnings. This change is required to remove the old HintCode `UNREACHABLE_SWITCH_CASE`.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages …
> Migrate UNREACHABLE_SWITCH_CASE from Hint to Warning

- LibTest/io/IOSink/IOSink_class_A01_t01.dart
- LibTest/io/IOSink/writeln_A01_t01.dart
Now these tests assept both `write(object);write('\n');` and `write('$object\n');`
> Fixes #2800. Change expectations for `IOSink.writeln()` tests

- LanguageFeatures/Wildcards/binding_A03_t02.dart
The change suggested in #2815 just updates expected error position, but in case of `unspecified` error position is ignored. Therefore, I believe, the intention was to update error code as well. Updated.
> Fixes #2815. Update expected warnings in binding_A03_t02.dart

- LanguageFeatures/Wildcards/local_functions_A01_t01.dart
There are no ways to force test runner to report this error for one particular test. We never expect `DEAD_CODE` warning in co19 tests. So, the only thing that we can to do is to remove this expectation.
> Fixes #2816. Don't expect DEAD_CODE warning

- LanguageFeatures/Augmentation-libraries/augmenting_types_A07_t01.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A07_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A07_t02.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A07_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A07_t07.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A07_t07_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t01.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t02.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t03.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t03_lib1.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t03_lib2.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t04.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t05.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t05_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t06.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t06_lib1.dart
- LanguageFeatures/Augmentation-libraries/augmenting_types_A10_t06_lib2.dart
There can be questions regarding `augmenting_types_A10_t03.dart` and `augmenting_types_A10_t06.dart`.  There are scoping tests checking that it is a compile-time error if we have a static and an instance member with the same name in an introductory and augmenting scopes. To avoid duplications these tests rewritten to have these declarations in different augmenting scopes.
> #2559. Add extension types to augmenting types tests

- LanguageFeatures/Parts-with-imports/scope_A02_t03_part2.dart
- LanguageFeatures/Parts-with-imports/scope_lib5.dart
Updated tests passes on the freshly built SDK.
> Fixes #2857. Fix names conflict in scope_A02_t03_part2.dart

- LanguageFeatures/Parts-with-imports/scope_A03_t02_part1.dart
The updated tests pass in a freshly built SDK
> Fixes #2858. Fix syntax error in scope_A03_t02_part1.dart

- LanguageFeatures/Parts-with-imports/scope_A03_t03_part1.dart
The updated test works in the latest SDK. @eernstg is it expected that extension types can be loaded defferedly?
> Fixes #2859. Hide public extension methods if an import is deferred

- LanguageFeatures/Parts-with-imports/scope_A04_t01_part2.dart
> Fixes #2860. Remove accidental code from scope_A04_t01_part2.dart

- LanguageFeatures/Parts-with-imports/scope_A05_t01_part1.dart
- LanguageFeatures/Parts-with-imports/scope_A05_t01_part2.dart
> Fixes #2861. Hide public extension methods if an import is deferred

- LanguageFeatures/Parts-with-imports/grammar_A05_t01.dart
- LanguageFeatures/Parts-with-imports/grammar_A05_t01_lib.dart
- LanguageFeatures/Parts-with-imports/grammar_A05_t02.dart
- LanguageFeatures/Parts-with-imports/grammar_A05_t02_lib.dart
- LanguageFeatures/Parts-with-imports/terminology_A04_t01.dart
- LanguageFeatures/Parts-with-imports/terminology_A04_t01_part1.dart
- LanguageFeatures/Parts-with-imports/terminology_A04_t01_part2.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t01.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t01_lib1.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t01_lib2.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t02.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t02_lib1.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t02_lib2.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t03.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t03_lib.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t04.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t04_lib1.dart
- LanguageFeatures/Parts-with-imports/terminology_A05_t04_lib2.dart
This PR maily contains tests that were moved from `Augmentation-libraries` folder, because statements that they check now part of "Parts with imports" feature.
> #2825. Add more grammar and terminology tests

- LibTest/async/Stream/Stream.fromIterable_A01_t01.dart
- LibTest/async/Stream/Stream.fromIterable_A01_t02.dart
- LibTest/async/Stream/Stream.fromIterable_A02_t01.dart
- LibTest/async/Stream/elementAt_A01_t01.test.dart
- LibTest/async/Stream/elementAt_A01_t02.test.dart
- LibTest/async/Stream/elementAt_A01_t03.test.dart
- LibTest/async/Stream/elementAt_A02_t01.test.dart
- LibTest/async/Stream/elementAt_A03_t01.test.dart
- LibTest/async/Stream/firstWhere_A04_t01.test.dart
- LibTest/async/Stream/first_A01_t01.test.dart
- LibTest/async/Stream/first_A02_t01.test.dart
- LibTest/async/Stream/first_A02_t02.test.dart
- LibTest/async/Stream/first_A03_t01.test.dart
- LibTest/async/Stream/first_A04_t01.test.dart
- LibTest/async/Stream/isEmpty_A01_t01.test.dart
- LibTest/async/Stream/isEmpty_A02_t01.test.dart
- LibTest/async/Stream/isEmpty_A03_t01.test.dart
- LibTest/async/Stream/isEmpty_A04_t01.test.dart
This also fixes https://github.com/dart-lang/sdk/issues/49264. Updated tests use `Stream.map` to check that the subscription was cancelled and there are no new events. The updated tests pass.
> Fixes #2930. Fix failing Stream tests.

- Utils/tests/Expect/notIdentical_A01_t01.dart
The test failed on web. Let's don't check identity of string literals here.
> Fixes #2938. Remove string literals identity check

- LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_A05_t02.dart
- LanguageFeatures/Control-flow-collections/Null-aware-elements/syntax_equality_A01_t01.dart
- LanguageFeatures/Control-flow-collections/Null-aware-elements/warnings_A01_t04.dart
There are more tests that have `TODO(sgrekhov): replace unspecified by the actual lint name`. I'll update them in a separate PR
> Fixes #2967. Update/ignore invalid_null_aware_operator warnings

- LanguageFeatures/FinalizationRegistry/ffi/Finalizer/Finalizer_A01_t04.dart
- LanguageFeatures/FinalizationRegistry/gc_utils_lib.dart
See https://github.com/dart-lang/sdk/issues/59752
> Fix Finalizer_A01_t04.dart test

- Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_initializer_list_t01.dart
- Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_initializer_list_t02.dart
- Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_initializer_list_t03.dart
- Language/Classes/Constructors/Constant_Constructors/not_a_constant_in_initializer_list_t04.dart
Github shows a wrong diff as if `..._02` was renamed to `...t03` and `...t03` to `...t02`. Hope that it won't be a problem for the review.
> Fixes #3030. Add additional test checking non const in a const constructor initializer list

- LanguageFeatures/Static-access-shorthand/non_ambiguity_A01_t01.dart
- LanguageFeatures/Static-access-shorthand/non_ambiguity_A01_t02.dart
- LanguageFeatures/Static-access-shorthand/non_ambiguity_A02_t01.dart
- LanguageFeatures/Static-access-shorthand/non_ambiguity_A02_t02.dart
- LanguageFeatures/Static-access-shorthand/non_ambiguity_A02_t03.dart
- LanguageFeatures/Static-access-shorthand/non_ambiguity_A02_t04.dart
- LanguageFeatures/Static-access-shorthand/non_ambiguity_A02_t05.dart
- LanguageFeatures/Static-access-shorthand/non_ambiguity_A02_t06.dart
Based on https://github.com/dart-lang/language/issues/4218#issuecomment-2565635559
> #2976. Add non-ambiguity tests

- Language/Expressions/Function_Invocation/Function_Expression_Invocation/call_A04_t01.dart
- Language/Expressions/Function_Invocation/Function_Expression_Invocation/call_A04_t02.dart
- Language/Expressions/Function_Invocation/Function_Expression_Invocation/call_A04_t03.dart
- Language/Expressions/Function_Invocation/Function_Expression_Invocation/call_A04_t04.dart
- Language/Expressions/Function_Invocation/Function_Expression_Invocation/call_A04_t05.dart
- Language/Expressions/Function_Invocation/Function_Expression_Invocation/call_A04_t06.dart
- Language/Expressions/Function_Invocation/Function_Expression_Invocation/call_A04_t07.dart
Based on the [test](https://dartpad.dev/?id=20c5ad78d018c515d829ff4e7191822f) mentioned in https://github.com/dart-lang/sdk/issues/55803#issuecomment-2124182059
> #2138. Add more tests for `call` method/getter

- Language/Expressions/Property_Extraction/Instance_Method_Closurization/method_closurization_named_params_A03_t01.dart
- Language/Expressions/Property_Extraction/Instance_Method_Closurization/method_closurization_named_params_A03_t02.dart
- Language/Expressions/Property_Extraction/Instance_Method_Closurization/method_closurization_named_params_A03_t03.dart
- Language/Expressions/Property_Extraction/Instance_Method_Closurization/method_closurization_positional_params_A03_t01.dart
- Language/Expressions/Property_Extraction/Instance_Method_Closurization/method_closurization_positional_params_A03_t02.dart
- Language/Expressions/Property_Extraction/Instance_Method_Closurization/method_closurization_positional_params_A03_t03.dart
If this PR is Ok I'll add the same tests for mixins, extension types etc in the next one.
> #3054. Add covariant parameters tests

- TypeSystem/flow-analysis/reachability_A12_t01.dart
- TypeSystem/flow-analysis/reachability_A12_t02.dart
- TypeSystem/flow-analysis/reachability_A12_t03.dart
- TypeSystem/flow-analysis/reachability_A12_t04.dart
We have `promotion_via_type_test_A*.dart` test that check promotion. So, only missing cases added here.
> #3057. Add instance check tests

- TypeSystem/flow-analysis/reachability_A22_t01.dart
- TypeSystem/flow-analysis/reachability_A22_t02.dart
- TypeSystem/flow-analysis/reachability_A22_t03.dart
- TypeSystem/flow-analysis/reachability_A22_t04.dart
- TypeSystem/flow-analysis/reachability_A22_t05.dart
- TypeSystem/flow-analysis/reachability_A22_t06.dart
- TypeSystem/flow-analysis/reachability_A22_t07.dart
Please review. In the [spec](https://github.com/dart-lang/language/blob/main/resources/type-system/flow-analysis.md#expressions) we also have:
> Binary operator: All binary operators other than `==`, `&&`, `||`, and `??` are handled as calls to the appropriate operator method.
So, if these tests are Ok, then I'm going to add the similar tests for `E1 + E2` and all other operators with two operands.
> #3057. Add tests for method invocation

- TypeSystem/flow-analysis/reachability_for_A01_t03.dart
- TypeSystem/flow-analysis/reachability_for_A01_t04.dart
- TypeSystem/flow-analysis/reachability_for_A01_t05.dart
- TypeSystem/flow-analysis/reachability_for_A01_t06.dart
- TypeSystem/flow-analysis/reachability_for_A01_t07.dart
- TypeSystem/flow-analysis/reachability_for_A01_t08.dart
- TypeSystem/flow-analysis/reachability_for_A01_t09.dart
- TypeSystem/flow-analysis/reachability_for_A01_t10.dart
- TypeSystem/flow-analysis/reachability_for_A01_t11.dart
- TypeSystem/flow-analysis/reachability_for_A01_t12.dart
- TypeSystem/flow-analysis/reachability_for_A03_t06.dart
- TypeSystem/flow-analysis/reachability_for_A03_t07.dart
It turns out that flow analysis after `break` statement can be not intuitive :)
> #3057. Add more for-statement tests

- LanguageFeatures/Static-access-shorthand/constant_expression_A10_t17.dart
The previous change in this test was wrong.  `static M one = const MC(1);` is not a potentially constant and therefore cannot be used in a constant expression.
> #3122. Expect an error in case of non-constant in a constant expression

- TypeSystem/flow-analysis/promotion_via_assignment_A03_t02.dart
According to the https://github.com/dart-lang/sdk/issues/60646#issuecomment-2848198769
> #3057. Update promotion_via_assignment_A03_t02.dart according to the implementation

- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t01.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t02.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t03.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t03_lib.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t04.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t05.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A02_t05_lib.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A03_t01.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A03_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A03_t02.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A03_t02_lib.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A03_t03.dart
- LanguageFeatures/Augmentation-libraries/type_inheritance_A03_t03_lib.dart
The A02 tests are updated such that they satisfy the constraint that member implementations can be provided by an augmentation, but not overridden. The A03 tests are updated to test abstract instance variables (and several cases handling augmentation of other variables have been deleted because concrete variables cannot be augmented according to the new specification of augmentations).
> #3182. Update type_inheritance_A02/3_t*.dart

- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A01_t01.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A01_t02.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A01_t03.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A01_t04.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A01_t05.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A01_t06.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t01.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t01_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t02.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t02_lib1.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t02_lib2.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t03.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t03_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t04.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t04_lib.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t05.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t06.dart
- LanguageFeatures/Augmentation-libraries/augmenting_declarations_A02_t07.dart
- Updated assertions and descriptions 
- Augmenting typedefs removed
- Augmenting non-abstract variables removed
- Augmenting bodies of functions/getters/setters removed
> #3182. Update augmenting_declarations_A01/02_*.dart tests

- LibTest/io/RawSecureServerSocket/single_A01_t03.dart
Use `Completer` to make sure that `RawSecureServerSocket.single` is called after the second write operation.
> Fixes #3219. Call `RawSecureServerSocket.single` after the second write operation

- LibTest/js_interop/JSArray/from_t01.dart
- LibTest/js_interop/JSArray/from_t02.dart
- LibTest/js_interop/JSArray/new_t01.dart
- LibTest/js_interop/JSArray/withLength_t01.dart
`from_t0*` also check `[]=` and `[]` operators. I don't think that we need any separate tests for them.
> #3180. Add `JSArray` tests.

- LibTest/js_interop/NullRejectionException/nullRejectionException_t01.dart
- LibTest/js_interop/NullRejectionException/nullRejectionException_t02.dart
There is also a public constructor `NullRejectionException.new` but I didn't find a way how it can be used. @srujzs do you know it? Does it makes sense to make it public?
> #3180. Add `NullRejectionException` tests

- LibTest/js_interop/JSExport/jsExport_A01_t06.dart
- LibTest/js_interop/JSExport/jsExport_A01_t07.dart
- LibTest/js_interop/JSExport/jsExport_A01_t08.dart
- LibTest/js_interop/JSExport/jsExport_A02_t01.dart
- LibTest/js_interop/JSExport/jsExport_A02_t02.dart
- LibTest/js_interop/JSExport/jsExport_A02_t03.dart
- LibTest/js_interop/JSExport/jsExport_A02_t04.dart
- LibTest/js_interop/JSExport/jsExport_A02_t05.dart
- LibTest/js_interop/JSExport/jsExport_A03_t01.dart
- LibTest/js_interop/JSExport/jsExport_A03_t02.dart
There are some tests in this PR that check the `@JSExport` annotation when applied to extension types and extensions. The current behavior is that this annotation is a no-op when applied to an extension type or extension, and it produces a compile-time error when a member of an extension type or extension is annotated with this annotation. The tests are written accordingly. Please review.
> #3180. Add JSExport tests. Part 2.

- Language/Classes/Getters/same_name_method_t08.dart
- Language/Classes/Getters/same_name_method_t09.dart
- Language/Classes/Getters/same_name_method_t12.dart
- Language/Classes/Getters/static_getter_t03.dart
- Language/Classes/Getters/static_getter_t04.dart
- Language/Classes/Setters/static_setter_t07.dart
- Language/Classes/Setters/static_setter_t08.dart
- Language/Classes/Setters/static_setter_t09.dart
- Language/Functions/syntax_t33.dart
- Language/Libraries_and_Scripts/Parts/compilation_t01.dart
- Language/Overview/Scoping/conflicting_names_t01.dart
- Language/Overview/Scoping/conflicting_names_t02.dart
- Language/Overview/Scoping/conflicting_names_t04.dart
- Language/Overview/Scoping/conflicting_names_t06.dart
- Language/Overview/Scoping/conflicting_names_t09.dart
- Language/Overview/Scoping/conflicting_names_t11.dart
- Language/Overview/Scoping/conflicting_names_t13.dart
- LanguageFeatures/Extension-types/static_analysis_extension_types_A03_t02.dart
- LanguageFeatures/Extension-types/static_analysis_extension_types_A11_t01.dart
- LanguageFeatures/Wildcards/other_declarations_A05_t33.dart
All tests from this PR now passing on CFE
> Fixes #3261. Update expected errors positions for CFE

- Language/Classes/Constructors/Factories/inference_A01_t01.dart
- Language/Classes/Constructors/Factories/inference_lib.dart
A strange issue. Sometimes the error was disappiering after renaming of the class. No error with the new SDK.
> Fixes #3297. Add tests about redirecting factory constructor inference

- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A01_t01.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A01_t02.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A01_t03.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A01_t04.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A01_t05.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A01_t06.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A02_t01.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A02_t02.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A02_t03.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A02_t04.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A03_t01.dart
- LibTest/js_interop/FunctionToJSExportedDartFunction/toJSCaptureThis_A04_t01.dart
Please note that I use `Expect.equals(globalContext, pThis);` to check the value of `this`. Is it Ok to make an assumption that `this == globalContext`?
> #3180. Add tests for `FunctionToJSExportedDartFunction`. Part 2.
